#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=blissc
MANUFACTURER=htc

#mkdir -p 
adb shell ls /system/bin/akmd
#chmod 755 /akmd
adb shell ls /system/bin/awb_camera
adb shell ls /system/bin/bma150_usr
adb shell ls /system/bin/dmagent
adb shell ls /system/bin/htc_ebdlogd
adb shell ls /system/bin/logcat2
adb shell ls /system/bin/lsc_camera
adb shell ls /system/bin/rmt_storag
adb shell ls /system/bin/snd
adb shell ls /system/bin/snd8k
adb shell ls /system/etc/AudioBTID.csv
adb shell ls /system/lib/egl/libEGL_adreno200.so
adb shell ls /system/lib/egl/libGLESv1_CM_adreno200.so 
adb shell ls /system/lib/egl/libGLESv2_adreno200.so 
adb shell ls /system/lib/egl/libq3dtools_adreno200.so 
adb shell ls /system/lib/libgsl.so 
adb shell ls /system/lib/libhtc_acoustic.so 
adb shell ls /system/lib/libaudioalsa.so 
adb shell ls /system/lib/libcamera.so 
adb shell ls /system/lib/liboemcamera.so 
adb shell ls /system/lib/libposteffect.so 
adb shell ls /system/lib/libgemini.so 
adb shell ls /system/lib/libmmipl.so 
adb shell ls /system/lib/libmmjpeg.so 
adb shell ls /system/lib/libhtc_ril.so
adb shell ls /system/lib/libims_ril.so 
adb shell ls /system/lib/libreference-ril.so 
adb shell ls /system/lib/libril_status.so 
adb shell ls /system/lib/libril.so 

#(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

