#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=blissc
MANUFACTURER=htc.hm

#mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/akmd /system/bin/akmd
#chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/akmd
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/awb_camera /system/bin/awb_camera 
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/bma150_usr /system/bin/bma150_usr
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dmagent /system/bin/dmagent 
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/htc_ebdlogd /system/bin/htc_ebdlogd
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/logcat2 /system/bin/logcat2
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lsc_camera /system/bin/lsc_camera
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rmt_storage /system/bin/rmt_storage
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/snd /system/bin/snd
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/snd8k /system/bin/snd8k
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/AudioBTID.csv /system/etc/AudioBTID.csv
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libEGL_adreno200.so /system/lib/egl/libEGL_adreno200.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv1_CM_adreno200.so /system/lib/egl/libGLESv1_CM_adreno200.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2_adreno200.so /system/lib/egl/libGLESv2_adreno200.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libq3dtools_adreno200.so /system/lib/egl/libq3dtools_adreno200.so 
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libgsl.so /system/lib/libgsl.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libhtc_acoustic.so /system/lib/libhtc_acoustic.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libaudioalsa.so /system/lib/libaudioalsa.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libcamera.so /system/lib/libcamera.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/liboemcamera.so /system/lib/liboemcamera.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libposteffect.so /system/lib/libposteffect.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libgemini.so /system/lib/libgemini.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmmipl.so /system/lib/libmmipl.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmmjpeg.so /system/lib/libmmjpeg.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libhtc_ril.so /system/lib/libhtc_ril.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libims_ril.so /system/lib/libims_ril.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libreference-ril.so /system/lib/libreference-ril.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libril_status.so /system/lib/libril_status.so
adb push ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libril.so /system/lib/libril.so

#(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
#ls: /system/bin/akmd: No such file or directory
#ls: /system/bin/awb_camera: No such file or directory
#ls: /system/bin/bma150_usr: No such file or directory
#ls: /system/bin/dmagent: No such file or directory
#ls: /system/bin/htc_ebdlogd: No such file or directory
#ls: /system/bin/logcat2: No such file or directory
#ls: /system/bin/lsc_camera: No such file or directory
#ls: /system/bin/rmt_storag: No such file or directory
#ls: /system/bin/snd: No such file or directory
#ls: /system/bin/snd8k: No such file or directory
#/system/etc/AudioBTID.csv
#/system/lib/egl/libEGL_adreno200.so
#/system/lib/egl/libGLESv1_CM_adreno200.so
#/system/lib/egl/libGLESv2_adreno200.so
#/system/lib/egl/libq3dtools_adreno200.so
#/system/lib/libgsl.so
#/system/lib/libhtc_acoustic.so
#/system/lib/libaudioalsa.so
#ls: /system/lib/libcamera.so: No such file or directory
#ls: /system/lib/liboemcamera.so: No such file or directory
#ls: /system/lib/libposteffect.so: No such file or directory
#ls: /system/lib/libgemini.so: No such file or directory
#ls: /system/lib/libmmipl.so: No such file or directory
#ls: /system/lib/libmmjpeg.so: No such file or directory
#ls: /system/lib/libhtc_ril.so: No such file or directory
#s: /system/lib/libims_ril.so: No such file or directory
#ls: /system/lib/libreference-ril.so: No such file or directory
#ls: /system/lib/libril_status.so: No such file or directory
#/system/lib/libril.so
